In [11]:
#importing libraries for the model
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
bank_note_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/training_set_label.csv" )

In [13]:
bank_note_data.head()
#getting a short insoght of data

VWTI     SWTI     CWTI        EI  Class
0  2.2634  -4.4862   3.6558 -0.612510      0
1  3.2718   1.7837   2.1161  0.613340      0
2 -3.9411 -12.8792  13.0597 -3.312500      1
3  0.5195  -3.2633   3.0895 -0.984900      0
4  2.5698  -4.4076   5.9856  0.078002      0

In [13]:
#importing test data
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/bank_note_data/testing_set_label.csv')

In [14]:
test_data.head()
#getting an insight of test data

VWTI      SWTI      CWTI       EI
0 -0.40804   0.54214  -0.52725  0.65860
1 -3.71810  -8.50890  12.36300 -0.95518
2  5.50400  10.36710  -4.41300 -4.02110
3  1.68490   8.74890  -1.26410 -1.38580
4  4.74320   2.10860   0.13680  1.65430

In [15]:
bank_note_data.shape


(1096, 5)

In [16]:
bank_note_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   VWTI    1096 non-null   float64
 1   SWTI    1096 non-null   float64
 2   CWTI    1096 non-null   float64
 3   EI      1096 non-null   float64
 4   Class   1096 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 42.9 KB


In [17]:
X=bank_note_data.drop("Class",axis=1)#components on which model is trained
y=bank_note_data['Class']#target 

In [18]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
#STep 1 building a model , for which we willl import some libraries and functions
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense


building layers and all

In [20]:
model=Sequential()
model.add(Dense(10,activation='relu',input_shape=(X_train.shape[1],)))
model.add(Dense(1,activation='sigmoid'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
#Compiling the Model
from tensorflow.keras.optimizers import RMSprop
optimizer=RMSprop(0.01)#learning rate of model is set as 0.01
model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['acc'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [22]:
#printing the summary of model
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 61
Trainable params: 61
Non-trainable params: 0
_________________________________________________________________


In [23]:
history=model.fit(X_train,y_train,validation_split=0.2,epochs=200,batch_size=30,verbose=1)

Train on 700 samples, validate on 176 samples
Epoch 1/200
700/700 [==============================] - 1s 810us/sample - loss: 0.5077 - acc: 0.7843 - val_loss: 0.2241 - val_acc: 0.9773
Epoch 2/200
700/700 [==============================] - 0s 68us/sample - loss: 0.1463 - acc: 0.9871 - val_loss: 0.0759 - val_acc: 0.9943
Epoch 3/200
700/700 [==============================] - 0s 46us/sample - loss: 0.0638 - acc: 0.9914 - val_loss: 0.0407 - val_acc: 1.0000
Epoch 4/200
700/700 [==============================] - 0s 46us/sample - loss: 0.0336 - acc: 1.0000 - val_loss: 0.0214 - val_acc: 1.0000
Epoch 5/200
700/700 [==============================] - 0s 46us/sample - loss: 0.0198 - acc: 1.0000 - val_loss: 0.0125 - val_acc: 1.0000
Epoch 6/200
700/700 [==============================] - 0s 46us/sample - loss: 0.0119 - acc: 1.0000 - val_loss: 0.0068 - val_acc: 1.0000
Epoch 7/200
700/700 [==============================] - 0s 57us/sample - loss: 0.0081 - acc: 1.0000 - val_loss: 0.0048 - val_acc: 1.0000
E

Epoch 58/200
700/700 [==============================] - 0s 34us/sample - loss: 2.0297e-08 - acc: 1.0000 - val_loss: 1.0045e-08 - val_acc: 1.0000
Epoch 59/200
700/700 [==============================] - 0s 34us/sample - loss: 2.0453e-08 - acc: 1.0000 - val_loss: 1.9647e-09 - val_acc: 1.0000
Epoch 60/200
700/700 [==============================] - ETA: 0s - loss: 8.9190e-11 - acc: 1.000 - 0s 38us/sample - loss: 1.8522e-08 - acc: 1.0000 - val_loss: 1.9700e-09 - val_acc: 1.0000
Epoch 61/200
700/700 [==============================] - 0s 34us/sample - loss: 1.3839e-08 - acc: 1.0000 - val_loss: 2.0662e-09 - val_acc: 1.0000
Epoch 62/200
700/700 [==============================] - 0s 46us/sample - loss: 1.0801e-08 - acc: 1.0000 - val_loss: 1.2302e-09 - val_acc: 1.0000
Epoch 63/200
700/700 [==============================] - 0s 46us/sample - loss: 9.5058e-09 - acc: 1.0000 - val_loss: 1.2277e-09 - val_acc: 1.0000
Epoch 64/200
700/700 [==============================] - 0s 46us/sample - loss: 8.3277e-0

700/700 [==============================] - 0s 46us/sample - loss: 5.7264e-10 - acc: 1.0000 - val_loss: 1.0662e-10 - val_acc: 1.0000
Epoch 171/200
700/700 [==============================] - 0s 57us/sample - loss: 5.9919e-10 - acc: 1.0000 - val_loss: 1.1330e-10 - val_acc: 1.0000
Epoch 172/200
700/700 [==============================] - 0s 46us/sample - loss: 7.2713e-10 - acc: 1.0000 - val_loss: 2.1020e-10 - val_acc: 1.0000
Epoch 173/200
700/700 [==============================] - 0s 57us/sample - loss: 5.9782e-10 - acc: 1.0000 - val_loss: 1.3447e-10 - val_acc: 1.0000
Epoch 174/200
700/700 [==============================] - 0s 46us/sample - loss: 5.4756e-10 - acc: 1.0000 - val_loss: 1.3594e-10 - val_acc: 1.0000
Epoch 175/200
700/700 [==============================] - 0s 46us/sample - loss: 5.4685e-10 - acc: 1.0000 - val_loss: 1.4039e-10 - val_acc: 1.0000
Epoch 176/200
700/700 [==============================] - 0s 34us/sample - loss: 5.8162e-10 - acc: 1.0000 - val_loss: 1.4724e-10 - val_acc:

In [27]:
model.evaluate(X_test,y_test)

220/220 [==============================] - 0s 95us/sample - loss: 1.6698e-07 - acc: 1.0000


[1.6698021878635937e-07, 1.0]

In [28]:
model.predict(test_data)

array([[1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.000000

In [26]:
answer=model.predict(test_data)

In [29]:
answer

array([[1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.0000000e+00],
       [0.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [0.000000

In [30]:
answer.dtype


dtype('float32')

In [58]:
answer.flatten()

array([1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e

In [32]:
ans=answer.flatten()

In [33]:
lis=list()

In [34]:
for x in ans:
    lis.append(int(x))
    
    

In [35]:
lis


[1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
